export type FacultyOptionValue =
  | 'ahs'
  | 'arts'
  | 'eng'
  | 'env'
  | 'math'
  | 'sci';
type FacultyOption = { value: FacultyOptionValue; label: string };
export const FACULTY_OPTIONS: FacultyOption[] = [
  { value: 'ahs', label: 'Applied Health Sciences' },
  { value: 'arts', label: 'Arts' },
  { value: 'eng', label: 'Engineering' },
  { value: 'env', label: 'Environment' },
  { value: 'math', label: 'Mathematics' },
  { value: 'sci', label: 'Science' },
];

export const PROGRAM_OPTIONS_BY_FACULTY = {
  ahs: [
    { value: 'Health Studies', label: 'Health Studies' },
    { value: 'Kinesiology', label: 'Kinesiology' },
    { value: 'Public Health', label: 'Public Health' },
    {
      value: 'Recreation and Leisure Studies',
      label: 'Recreation and Leisure Studies',
    },
    {
      value: 'Recreation and Sport Business',
      label: 'Recreation and Sport Business',
    },
    { value: 'Therapeutic Recreation', label: 'Therapeutic Recreation' },
    { value: 'Tourism Development', label: 'Tourism Development' },
  ],
  arts: [
    {
      value: 'Accounting and Financial Management',
      label: 'Accounting and Financial Management',
    },
    { value: 'Anthropology', label: 'Anthropology' },
    { value: 'Classical Studies', label: 'Classical Studies' },
    {
      value: 'Computing and Financial Management',
      label: 'Computing and Financial Management',
    },
    { value: 'Economics', label: 'Economics' },
    { value: 'English', label: 'English' },
    { value: 'Fine Arts', label: 'Fine Arts' },
    { value: 'French', label: 'French' },
    { value: 'Gender and Social Justice', label: 'Gender and Social Justice' },
    { value: 'German', label: 'German' },
    {
      value: 'Global Business and Digital Arts',
      label: 'Global Business and Digital Arts',
    },
    { value: 'History', label: 'History' },
    { value: 'Honours Arts', label: 'Honours Arts' },
    { value: 'Honours Arts and Business', label: 'Honours Arts and Business' },
    { value: 'Legal Studies', label: 'Legal Studies' },
    { value: 'Liberal Studies', label: 'Liberal Studies' },
    { value: 'Medieval Studies', label: 'Medieval Studies' },
    { value: 'Music', label: 'Music' },
    {
      value: 'Peace and Conflict Studies',
      label: 'Peace and Conflict Studies',
    },
    { value: 'Philosophy', label: 'Philosophy' },
    { value: 'Political Science', label: 'Political Science' },
    { value: 'Psychology', label: 'Psychology' },
    { value: 'Religious Studies', label: 'Religious Studies' },
    {
      value: 'Sexuality, Marriage, and Family Studies',
      label: 'Sexuality, Marriage, and Family Studies',
    },
    {
      value: 'Social Development Studies',
      label: 'Social Development Studies',
    },
    { value: 'Social Work', label: 'Social Work' },
    { value: 'Sociology', label: 'Sociology' },
    { value: 'Spanish', label: 'Spanish' },
    { value: 'Speech Communication', label: 'Speech Communication' },
    { value: 'Theatre and Performance', label: 'Theatre and Performance' },
  ],
  eng: [
    { value: 'Architectural Engineering', label: 'Architectural Engineering' },
    { value: 'Architecture', label: 'Architecture' },
    { value: 'Biomedical Engineering', label: 'Biomedical Engineering' },
    { value: 'Chemical Engineering', label: 'Chemical Engineering' },
    { value: 'Civil Engineering', label: 'Civil Engineering' },
    { value: 'Computer Engineering', label: 'Computer Engineering' },
    { value: 'Electrical Engineering', label: 'Electrical Engineering' },
    { value: 'Environmental Engineering', label: 'Environmental Engineering' },
    { value: 'Geological Engineering', label: 'Geological Engineering' },
    { value: 'Management Engineering', label: 'Management Engineering' },
    { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
    { value: 'Mechatronics Engineering', label: 'Mechatronics Engineering' },
    {
      value: 'Nanotechnology Engineering',
      label: 'Nanotechnology Engineering',
    },
    { value: 'Software Engineering', label: 'Software Engineering' },
    {
      value: 'Systems Design Engineering',
      label: 'Systems Design Engineering',
    },
  ],
  env: [
    { value: 'Environment and Business', label: 'Environment and Business' },
    {
      value: 'Environment, Resources and Sustainability',
      label: 'Environment, Resources and Sustainability',
    },
    { value: 'Geography and Aviation', label: 'Geography and Aviation' },
    {
      value: 'Geography and Environmental Management',
      label: 'Geography and Environmental Management',
    },
    { value: 'Geomatics', label: 'Geomatics' },
    { value: 'International Development', label: 'International Development' },
    { value: 'Knowledge Integration', label: 'Knowledge Integration' },
    { value: 'Planning', label: 'Planning' },
  ],
  math: [
    { value: 'Actuarial Science', label: 'Actuarial Science' },
    { value: 'Applied Mathematics', label: 'Applied Mathematics' },
    { value: 'Biostatistics', label: 'Biostatistics' },
    {
      value:
        'Business Administration (Laurier) and Computer Science (Waterloo) Double Degree',
      label:
        'Business Administration (Laurier) and Computer Science (Waterloo) Double Degree',
    },
    {
      value:
        'Business Administration (Laurier) and Mathematics (Waterloo) Double Degree',
      label:
        'Business Administration (Laurier) and Mathematics (Waterloo) Double Degree',
    },
    {
      value: 'Combinatorics and Optimization',
      label: 'Combinatorics and Optimization',
    },
    { value: 'Computational Mathematics', label: 'Computational Mathematics' },
    { value: 'Computer Science', label: 'Computer Science' },
    { value: 'Data Science', label: 'Data Science' },
    {
      value: 'Computing and Financial Management',
      label: 'Computing and Financial Management',
    },
    {
      value: 'Information Technology Management',
      label: 'Information Technology Management',
    },
    { value: 'Mathematical Economics', label: 'Mathematical Economics' },
    { value: 'Mathematical Finance', label: 'Mathematical Finance' },
    { value: 'Mathematical Optimization', label: 'Mathematical Optimization' },
    { value: 'Mathematical Physics', label: 'Mathematical Physics' },
    { value: 'Mathematical Studies', label: 'Mathematical Studies' },
    { value: 'Mathematics', label: 'Mathematics' },
    {
      value: 'Mathematics/Business Administration',
      label: 'Mathematics/Business Administration',
    },
    {
      value: 'Mathematics/Chartered Professional Accounting',
      label: 'Mathematics/Chartered Professional Accounting',
    },
    {
      value: 'Mathematics/Financial Analysis and Risk Management',
      label: 'Mathematics/Financial Analysis and Risk Management',
    },
    { value: 'Mathematics Teaching', label: 'Mathematics Teaching' },
    { value: 'Pure Mathematics', label: 'Pure Mathematics' },
    { value: 'Statistics', label: 'Statistics' },
  ],
  sci: [
    { value: 'Biochemistry', label: 'Biochemistry' },
    { value: 'Biology', label: 'Biology' },
    { value: 'Biomedical Sciences', label: 'Biomedical Sciences' },
    {
      value: 'Biotechnology/Chartered Professional Accounting',
      label: 'Biotechnology/Chartered Professional Accounting',
    },
    { value: 'Biotechnology/Economics', label: 'Biotechnology/Economics' },
    { value: 'Chemistry', label: 'Chemistry' },
    { value: 'Earth Sciences', label: 'Earth Sciences' },
    { value: 'Environmental Science', label: 'Environmental Science' },
    { value: 'Honours Science', label: 'Honours Science' },
    { value: 'Life Physics', label: 'Life Physics' },
    { value: 'Life Sciences', label: 'Life Sciences' },
    { value: 'Physical Sciences', label: 'Physical Sciences' },
    { value: 'Psychology', label: 'Psychology' },
    {
      value: 'Materials and Nanosciences',
      label: 'Materials and Nanosciences',
    },
    { value: 'Mathematical Physics', label: 'Mathematical Physics' },
    { value: 'Medicinal Chemistry', label: 'Medicinal Chemistry' },
    { value: 'Optometry', label: 'Optometry' },
    { value: 'Pharmacy', label: 'Pharmacy' },
    { value: 'Physics', label: 'Physics' },
    { value: 'Physics and Astronomy', label: 'Physics and Astronomy' },
    { value: 'Science and Aviation', label: 'Science and Aviation' },
    { value: 'Science and Business', label: 'Science and Business' },
  ],
};

export const FROM_OPTIONS = [
  { value: 'Anguilla', label: 'Anguilla' },
  { value: 'Antigua & Barbuda', label: 'Antigua & Barbuda' },
  { value: 'Aruba', label: 'Aruba' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Bonaire', label: 'Bonaire' },
  { value: 'British Virgin Islands', label: 'British Virgin Islands' },
  { value: 'Cayman Islands', label: 'Cayman Islands' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Curaçao', label: 'Curaçao' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guadeloupe', label: 'Guadeloupe' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Martinique', label: 'Martinique' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'St Kitts & Nevis', label: 'St Kitts & Nevis' },
  { value: 'St Lucia', label: 'St Lucia' },
  { value: 'Saint Martin', label: 'Saint Martin' },
  {
    value: 'Saint Vincent & the Grenadines',
    label: 'Saint Vincent & the Grenadines',
  },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Sint Maarten', label: 'Sint Maarten' },
  { value: 'Trinidad & Tobago', label: 'Trinidad & Tobago' },
  { value: 'Turks and Caicos Islands', label: 'Turks and Caicos Islands' },
  {
    value: 'United States Virgin Islands',
    label: 'United States Virgin Islands',
  },
  { value: '', label: '-------' },
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia Herzegovina', label: 'Bosnia Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina', label: 'Burkina' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Cape Verde', label: 'Cape Verde' },
  { value: 'Central African Rep', label: 'Central African Rep' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo', label: 'Congo' },
  { value: 'Congo {Democratic Rep}', label: 'Congo {Democratic Rep}' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'East Timor', label: 'East Timor' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland {Republic}', label: 'Ireland {Republic}' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Ivory Coast', label: 'Ivory Coast' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Korea North', label: 'Korea North' },
  { value: 'Korea South', label: 'Korea South' },
  { value: 'Kosovo', label: 'Kosovo' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macedonia', label: 'Macedonia' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia', label: 'Micronesia' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar, {Burma}', label: 'Myanmar, {Burma}' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russian Federation', label: 'Russian Federation' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome & Principe', label: 'Sao Tome & Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Swaziland', label: 'Swaziland' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Vatican City', label: 'Vatican City' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
];

const currentYear = new Date().getFullYear();
const numYearOptions = 8;
export const START_YEAR_OPTIONS = Array(numYearOptions)
  .fill(0)
  .map((_, index) => {
    const year = (currentYear - index).toString();
    return { label: year, value: year };
  });

export const START_TERM_OPTIONS = [
  { label: 'Fall', value: 'fall' },
  { label: 'Winter', value: 'winter' },
  { label: 'Spring', value: 'spring' },
];
