export const POSITIONS_OPTIONS = [
  // { value: 'president', label: 'President' },
  // { value: 'vice-president', label: 'Vice-President' },
  // { value: 'secretary', label: 'Secretary' },
  {
    value: 'treasurer',
    label: 'Treasurer',
    emoji: '💰',
    ariaLabel: 'money bag',
    winner: 'Tia Lewis',
  },
  {
    value: 'public relations officer',
    label: 'Public Relations Officer',
    emoji: '📢',
    ariaLabel: 'loudspeaker',
    winner: 'Jacinta Sandi',
  },
  {
    value: 'publications officer',
    label: 'Publications Officer',
    emoji: '🎭',
    ariaLabel: 'performing arts',
    winner: 'Joshua Worme',
  },
  {
    value: 'web administrator',
    label: 'Web Administrator',
    emoji: '💻',
    ariaLabel: 'laptop',
    winner: 'Christopher Mohammed',
  },
  {
    value: 'social coordinator',
    label: 'Social Coordinator',
    emoji: '🎉',
    ariaLabel: 'tada',
    winner: 'Lyam Mapp and Jenny Cheung',
  },
  // {
  //   value: 'sports coordinator',
  //   label: 'Sports Coordinator',
  //   emoji: '⚽️',
  //   ariaLabel: 'football',
  // },
  {
    value: 'education coordinator',
    label: 'Education Coordinator',
    emoji: '📚',
    ariaLabel: 'books',
    winner: 'Amanda Chatoor',
  },
  {
    value: '1st year coordinator',
    label: '1st Year Coordinator',
    emoji: '👩‍🎓',
    ariaLabel: 'woman student',
    winner: 'Lachlan Barker',
  },
];
